/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gajiKaryawan;

import javax.swing.JOptionPane;

/**
 *
 * @author LENOVO
 */
public class no1 extends javax.swing.JFrame {
    
    private int tarifPerJam;
    private int jamKerja;

    /**
     * Creates new form no1
     */
    public no1() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        btnBruto = new javax.swing.JButton();
        btnBersih = new javax.swing.JButton();
        tfJamKerja = new javax.swing.JTextField();
        tfTarifPerJam = new javax.swing.JTextField();
        tfBruto = new javax.swing.JTextField();
        tfBersih = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        btnKeluar = new javax.swing.JButton();
        btnReset = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel1.setText("PERHITUNGAN GAJI KARYAWAN");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(106, 22, 294, 21);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setText("Jumlah jam kerja 1 minggu      :");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(77, 125, 192, 20);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setText("Tarif / Jam                               :");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(79, 186, 190, 20);

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setText("Gaji Bruto                                :");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(79, 312, 192, 20);

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel5.setText("Gaji Bersih                                :");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(79, 414, 195, 20);

        btnBruto.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btnBruto.setText("Hitung Gaji Bruto");
        btnBruto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBrutoActionPerformed(evt);
            }
        });
        getContentPane().add(btnBruto);
        btnBruto.setBounds(153, 250, 222, 24);

        btnBersih.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btnBersih.setText("Hitung Gaji Bersih");
        btnBersih.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBersihActionPerformed(evt);
            }
        });
        getContentPane().add(btnBersih);
        btnBersih.setBounds(154, 368, 220, 24);

        tfJamKerja.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfJamKerjaActionPerformed(evt);
            }
        });
        getContentPane().add(tfJamKerja);
        tfJamKerja.setBounds(287, 121, 81, 31);

        tfTarifPerJam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfTarifPerJamActionPerformed(evt);
            }
        });
        getContentPane().add(tfTarifPerJam);
        tfTarifPerJam.setBounds(312, 182, 127, 31);

        tfBruto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfBrutoActionPerformed(evt);
            }
        });
        getContentPane().add(tfBruto);
        tfBruto.setBounds(289, 308, 150, 31);

        tfBersih.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfBersihActionPerformed(evt);
            }
        });
        getContentPane().add(tfBersih);
        tfBersih.setBounds(292, 410, 147, 31);

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel6.setText("Jam");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(374, 125, 24, 20);

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel7.setText("Rp.");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(287, 186, 19, 20);

        btnKeluar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnKeluar.setText("Keluar");
        btnKeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKeluarActionPerformed(evt);
            }
        });
        getContentPane().add(btnKeluar);
        btnKeluar.setBounds(423, 467, 72, 27);

        btnReset.setText("Reset");
        btnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetActionPerformed(evt);
            }
        });
        getContentPane().add(btnReset);
        btnReset.setBounds(30, 470, 72, 23);
        getContentPane().add(jLabel8);
        jLabel8.setBounds(0, 0, 510, 510);

        jPanel1.setBackground(new java.awt.Color(234, 255, 234));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 510, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 510, 100);

        jPanel2.setBackground(new java.awt.Color(255, 255, 204));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 510, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 410, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel2);
        jPanel2.setBounds(0, 100, 510, 410);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBersihActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBersihActionPerformed
        // TODO add your handling code here:
        try {
            // Periksa apakah tarifPerJam dan jamKerja sudah diisi
            if (tarifPerJam == 0 || jamKerja == 0) {
                JOptionPane.showMessageDialog(this, "Isi jumlah jam kerja dan tarif per jam terlebih dahulu.");
                return;
            } else if (tarifPerJam <= 0 || jamKerja <= 0 ) {
                JOptionPane.showMessageDialog(this, "Isi jumlah jam kerja dengan sesuai.");
            }
            

            // Konstanta pajak
            double pajak = 0.1;

            // Hitung gaji bruto berdasarkan jumlah jam kerja
            int gajiAwal;
            if (jamKerja <= 40) {
                gajiAwal = jamKerja * tarifPerJam;
            } else {
                gajiAwal = 40 * tarifPerJam + (jamKerja - 40) * (tarifPerJam * 15 / 10); // 1.5 kali lipat
            }

            // Hitung gaji bersih setelah potongan pajak
            double gajiBersih = gajiAwal - (gajiAwal * pajak);

            // Tampilkan hasil gaji bersih di dalam TextField tfBersih
            tfBersih.setText("Rp. " + gajiBersih);
            } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(this, "Masukkan jumlah jam kerja dan tarif per jam yang valid.");
        }
    }//GEN-LAST:event_btnBersihActionPerformed

    private void btnBrutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBrutoActionPerformed
        // TODO add your handling code here:
        try {
            if (tarifPerJam <= 0 || jamKerja <= 0 ) {
                JOptionPane.showMessageDialog(this, "Isi jumlah jam kerja dengan sesuai.");
                return;
            }
            
            // Dapatkan tarif per jam dan jumlah jam kerja dari input field
            tarifPerJam = Integer.parseInt(tfTarifPerJam.getText());
            jamKerja = Integer.parseInt(tfJamKerja.getText());

            // Hitung gaji bruto berdasarkan jumlah jam kerja
            int gajiAwal;
            if (jamKerja <= 40) {
                gajiAwal = jamKerja * tarifPerJam;
            } else {
                gajiAwal = 40 * tarifPerJam + (jamKerja - 40) * (tarifPerJam * 15 / 10); // 1.5 kali lipat
            } 

            // Tampilkan hasil gaji bruto di dalam TextField tfBruto
            tfBruto.setText("Rp. " + gajiAwal);
        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(this, "Masukkan jumlah jam kerja dan tarif per jam yang valid.");
        }
    }//GEN-LAST:event_btnBrutoActionPerformed

    private void tfJamKerjaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfJamKerjaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfJamKerjaActionPerformed

    private void tfTarifPerJamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfTarifPerJamActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfTarifPerJamActionPerformed

    private void tfBrutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfBrutoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfBrutoActionPerformed

    private void tfBersihActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfBersihActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfBersihActionPerformed

    private void btnKeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKeluarActionPerformed
        // TODO add your handling code here
        System.exit(0);
    }//GEN-LAST:event_btnKeluarActionPerformed

    private void btnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetActionPerformed
        // TODO add your handling code here:
        tfJamKerja.setText("");
        tfTarifPerJam.setText("");
        tfBruto.setText("");
        tfBersih.setText("");
    }//GEN-LAST:event_btnResetActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(no1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(no1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(no1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(no1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new no1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBersih;
    private javax.swing.JButton btnBruto;
    private javax.swing.JButton btnKeluar;
    private javax.swing.JButton btnReset;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField tfBersih;
    private javax.swing.JTextField tfBruto;
    private javax.swing.JTextField tfJamKerja;
    private javax.swing.JTextField tfTarifPerJam;
    // End of variables declaration//GEN-END:variables
}
