/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package warungMakan;

import javax.swing.JOptionPane;

/**
 *
 * @author LENOVO
 */
public class no2 extends javax.swing.JFrame {
    
    private int jumlahAwal = 0;

    /**
     * Creates new form no2
     */
    public no2() {
        initComponents();
        
        tfJumlah.setText(String.valueOf(jumlahAwal));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bgMenu = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tfPesanan = new javax.swing.JTextArea();
        tfHarga = new javax.swing.JTextField();
        btnKurang = new javax.swing.JButton();
        btnTambah = new javax.swing.JButton();
        btnBeli = new javax.swing.JButton();
        btnHapus = new javax.swing.JButton();
        btnKeluar = new javax.swing.JButton();
        tfJumlah = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        rbPangsit = new javax.swing.JRadioButton();
        rbCapcay = new javax.swing.JRadioButton();
        rbNasgor = new javax.swing.JRadioButton();
        rbWonton = new javax.swing.JRadioButton();
        rbKwetiau = new javax.swing.JRadioButton();
        rbMigor = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 218, 210));

        jLabel1.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 30)); // NOI18N
        jLabel1.setText("RUMAH MAKAN KITA");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(238, 238, 238)
                .addComponent(jLabel1)
                .addContainerGap(248, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(43, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(41, 41, 41))
        );

        getContentPane().add(jPanel1, java.awt.BorderLayout.PAGE_START);

        jPanel3.setBackground(new java.awt.Color(234, 234, 255));
        jPanel3.setLayout(null);

        jPanel2.setBackground(new java.awt.Color(221, 221, 255));

        jLabel10.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel10.setText("Harga    : ");

        jLabel11.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel11.setText("Jumlah   :");

        jLabel12.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel12.setText("Informasi Pesanan  :");

        tfPesanan.setEditable(false);
        tfPesanan.setColumns(20);
        tfPesanan.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        tfPesanan.setRows(5);
        jScrollPane1.setViewportView(tfPesanan);

        tfHarga.setEditable(false);
        tfHarga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfHargaActionPerformed(evt);
            }
        });

        btnKurang.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        btnKurang.setText("-");
        btnKurang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKurangActionPerformed(evt);
            }
        });

        btnTambah.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        btnTambah.setText("+");
        btnTambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTambahActionPerformed(evt);
            }
        });

        btnBeli.setText("Beli");
        btnBeli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBeliActionPerformed(evt);
            }
        });

        btnHapus.setText("Hapus");
        btnHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHapusActionPerformed(evt);
            }
        });

        btnKeluar.setText("Keluar");
        btnKeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKeluarActionPerformed(evt);
            }
        });

        tfJumlah.setEditable(false);
        tfJumlah.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        tfJumlah.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tfJumlah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfJumlahActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(54, 54, 54)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel10)
                                    .addComponent(jLabel11))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(tfHarga)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                        .addGap(0, 10, Short.MAX_VALUE)
                                        .addComponent(btnKurang, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(tfJumlah, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(btnTambah)
                                        .addGap(23, 23, 23))))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(btnBeli, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(25, 25, 25)
                                .addComponent(btnHapus, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel12)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 305, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(btnKeluar)))
                .addContainerGap(59, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(tfHarga, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(btnKurang)
                    .addComponent(btnTambah)
                    .addComponent(tfJumlah, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnBeli)
                    .addComponent(btnHapus))
                .addGap(60, 60, 60)
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(btnKeluar)
                .addGap(17, 17, 17))
        );

        jPanel3.add(jPanel2);
        jPanel2.setBounds(0, -1, 420, 510);

        jLabel2.setFont(new java.awt.Font("Rockwell Extra Bold", 0, 18)); // NOI18N
        jLabel2.setText("Menu    :");
        jPanel3.add(jLabel2);
        jLabel2.setBounds(570, 10, 88, 22);

        jLabel3.setIcon(new javax.swing.ImageIcon("C:\\Users\\LENOVO\\Pictures\\modul 2 no 2\\kwetiau-removebg-preview.png")); // NOI18N
        jPanel3.add(jLabel3);
        jLabel3.setBounds(440, 70, 150, 100);

        jLabel4.setIcon(new javax.swing.ImageIcon("C:\\Users\\LENOVO\\Pictures\\modul 2 no 2\\migor-removebg-preview.png")); // NOI18N
        jPanel3.add(jLabel4);
        jLabel4.setBounds(620, 70, 150, 100);

        jLabel5.setIcon(new javax.swing.ImageIcon("C:\\Users\\LENOVO\\Pictures\\modul 2 no 2\\nasgor-removebg-preview.png")); // NOI18N
        jPanel3.add(jLabel5);
        jLabel5.setBounds(450, 200, 130, 130);

        jLabel6.setIcon(new javax.swing.ImageIcon("C:\\Users\\LENOVO\\Pictures\\modul 2 no 2\\Wonton_pedas-removebg-preview.png")); // NOI18N
        jPanel3.add(jLabel6);
        jLabel6.setBounds(640, 210, 125, 120);

        jLabel7.setIcon(new javax.swing.ImageIcon("C:\\Users\\LENOVO\\Pictures\\modul 2 no 2\\pangsit_goreng-removebg-preview.png")); // NOI18N
        jPanel3.add(jLabel7);
        jLabel7.setBounds(450, 380, 140, 99);
        jPanel3.add(jLabel8);
        jLabel8.setBounds(386, 427, 0, 0);

        jLabel9.setIcon(new javax.swing.ImageIcon("C:\\Users\\LENOVO\\Pictures\\modul 2 no 2\\capcay_2-removebg-preview.png")); // NOI18N
        jPanel3.add(jLabel9);
        jLabel9.setBounds(630, 410, 140, 70);

        bgMenu.add(rbPangsit);
        rbPangsit.setText("Pangsit Goreng");
        rbPangsit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbPangsitActionPerformed(evt);
            }
        });
        jPanel3.add(rbPangsit);
        rbPangsit.setBounds(460, 480, 150, 21);

        bgMenu.add(rbCapcay);
        rbCapcay.setText("Capcay");
        rbCapcay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbCapcayActionPerformed(evt);
            }
        });
        jPanel3.add(rbCapcay);
        rbCapcay.setBounds(670, 480, 100, 21);

        bgMenu.add(rbNasgor);
        rbNasgor.setText("Nasgor");
        rbNasgor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbNasgorActionPerformed(evt);
            }
        });
        jPanel3.add(rbNasgor);
        rbNasgor.setBounds(480, 330, 110, 21);

        bgMenu.add(rbWonton);
        rbWonton.setText("Wonton Pedas");
        rbWonton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbWontonActionPerformed(evt);
            }
        });
        jPanel3.add(rbWonton);
        rbWonton.setBounds(650, 330, 130, 21);

        bgMenu.add(rbKwetiau);
        rbKwetiau.setText("Kwetiau");
        rbKwetiau.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbKwetiauActionPerformed(evt);
            }
        });
        jPanel3.add(rbKwetiau);
        rbKwetiau.setBounds(480, 170, 100, 21);

        bgMenu.add(rbMigor);
        rbMigor.setText("Migor");
        rbMigor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbMigorActionPerformed(evt);
            }
        });
        jPanel3.add(rbMigor);
        rbMigor.setBounds(670, 170, 80, 21);

        getContentPane().add(jPanel3, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tfHargaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfHargaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfHargaActionPerformed

    private void rbKwetiauActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbKwetiauActionPerformed
        // TODO add your handling code here:
        tfJumlah.setText("0");
        int harga = 15000;
        if (jumlahAwal == 0) {
            tfHarga.setText("Rp. " + 0);
        } else if (jumlahAwal > 0) {
            tfHarga.setText("Rp. " + harga);
        }
    }//GEN-LAST:event_rbKwetiauActionPerformed

    private void rbMigorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbMigorActionPerformed
        // TODO add your handling code here:
        tfJumlah.setText("0");
        int harga = 12000;
        if (jumlahAwal == 0) {
            tfHarga.setText("Rp. " + 0);
        } else if (jumlahAwal > 0) {
            tfHarga.setText("Rp. " + harga);
        }
    }//GEN-LAST:event_rbMigorActionPerformed

    private void rbNasgorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbNasgorActionPerformed
        // TODO add your handling code here:
        tfJumlah.setText("0");
        int harga = 12000;
        if (jumlahAwal == 0) {
            tfHarga.setText("Rp. " + 0);
        } else if (jumlahAwal > 0) {
            tfHarga.setText("Rp. " + harga);
        }
    }//GEN-LAST:event_rbNasgorActionPerformed
 
    private void rbWontonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbWontonActionPerformed
        // TODO add your handling code here:
        tfJumlah.setText("0");
        int harga = 17000;
        if (jumlahAwal == 0) {
            tfHarga.setText("Rp. " + 0);
        } else if (jumlahAwal > 0) {
            tfHarga.setText("Rp. " + harga);
        }
    }//GEN-LAST:event_rbWontonActionPerformed

    private void rbPangsitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbPangsitActionPerformed
        // TODO add your handling code here:
        tfJumlah.setText("0");
        int harga = 17000;
        if (jumlahAwal == 0) {
            tfHarga.setText("Rp. " + 0);
        } else if (jumlahAwal > 0) {
            tfHarga.setText("Rp. " + harga);
        }
    }//GEN-LAST:event_rbPangsitActionPerformed

    private void rbCapcayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbCapcayActionPerformed
        // TODO add your handling code here:
        tfJumlah.setText("0");
        int harga = 20000;
        if (jumlahAwal == 0) {
            tfHarga.setText("Rp. " + 0);
        } else if (jumlahAwal > 0) {
            tfHarga.setText("Rp. " + harga);
        }
    }//GEN-LAST:event_rbCapcayActionPerformed

    private void tfJumlahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfJumlahActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfJumlahActionPerformed
    
    private void btnTambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTambahActionPerformed
        // TODO add your handling code here:
        try {
            // Dapatkan nilai saat ini dari tfJumlah dan ubah menjadi tipe data numerik
            int nilaiSaatIni = Integer.parseInt(tfJumlah.getText());

            // Dapatkan harga dari radio button yang dipilih
            int harga = 0; // Inisialisasi dengan harga default 0

            if (rbKwetiau.isSelected()) {
                harga = 15000;
            } else if (rbMigor.isSelected()) {
                harga = 12000;
            } else if (rbNasgor.isSelected()) {
                harga = 12000;
            } else if (rbWonton.isSelected()) {
                harga = 17000;
            } else if (rbPangsit.isSelected()) {
                harga = 17000;
            } else if (rbCapcay.isSelected()) {
                harga = 20000;
            }

            // Tambahkan 1 ke nilai saat ini
            nilaiSaatIni++;

            // Perbarui nilai di tfJumlah
            tfJumlah.setText(Integer.toString(nilaiSaatIni));

            // Kalikan nilai dengan harga
            int totalHarga = nilaiSaatIni * harga;

            // Perbarui nilai di tfHarga
            tfHarga.setText("Rp. " + totalHarga);
        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(this, "Masukkan jumlah yang valid di tfJumlah.");
        }
    }//GEN-LAST:event_btnTambahActionPerformed

    private void btnKurangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKurangActionPerformed
        // TODO add your handling code here:
        try {
            // Dapatkan nilai saat ini dari tfJumlah dan ubah menjadi tipe data numerik
            int nilaiSaatIni = Integer.parseInt(tfJumlah.getText());

            // Dapatkan harga dari radio button yang dipilih
            int harga = 0; // Inisialisasi dengan harga default 0

            if (rbKwetiau.isSelected()) {
                harga = 15000;
            } else if (rbMigor.isSelected()) {
                harga = 12000;
            } else if (rbNasgor.isSelected()) {
                harga = 12000;
            } else if (rbWonton.isSelected()) {
                harga = 17000;
            } else if (rbPangsit.isSelected()) {
                harga = 17000;
            } else if (rbCapcay.isSelected()) {
                harga = 20000;
            }

            // Pastikan nilai tidak kurang dari 0
            nilaiSaatIni = Math.max(1, nilaiSaatIni);
            
            // Kurangkan 1 dari nilai saat ini
            nilaiSaatIni--;

            // Perbarui nilai di tfJumlah
            tfJumlah.setText(Integer.toString(nilaiSaatIni));

            // Kalikan nilai dengan harga
            int totalHarga = nilaiSaatIni * harga;

            // Perbarui nilai di tfHarga
            tfHarga.setText("Rp. " + totalHarga);
        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(this, "Masukkan jumlah yang valid di tfJumlah.");
        }
    }//GEN-LAST:event_btnKurangActionPerformed

    private void btnBeliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBeliActionPerformed
        // TODO add your handling code here:
        // Inisialisasi string untuk menyimpan data pesanan
        StringBuilder pesanan = new StringBuilder("Pesanan Anda :\n ========================== \n");

        // Cek setiap radio button makanan apakah dipilih
        if (rbKwetiau.isSelected()) {
            pesanan.append("Menu : Kwetiau\n");
        }
        if (rbMigor.isSelected()) {
            pesanan.append("Menu : Migor\n");
        }
        if (rbNasgor.isSelected()) {
            pesanan.append("Menu : Nasgor\n");
        }
        if (rbWonton.isSelected()) {
            pesanan.append("Menu : Wonton Pedas\n");
        }
        if (rbPangsit.isSelected()) {
            pesanan.append("Menu : Pangsit Goreng\n");
        }
        if (rbCapcay.isSelected()) {
            pesanan.append("Menu : Capcay\n");
        }

        // Tambahkan informasi jumlah dan harga ke pesanan
        int jumlah = Integer.parseInt(tfJumlah.getText());
        int harga = Integer.parseInt(tfHarga.getText().replaceAll("\\D", "")); // Hapus "Rp." dan ambil angka
        pesanan.append("Jumlah : ").append(jumlah).append("\n");
        pesanan.append("Harga : Rp. ").append(harga).append("\n");

        // Tambahkan pesanan ke tfPesanan
        tfPesanan.setText(pesanan.toString());
    }//GEN-LAST:event_btnBeliActionPerformed

    private void btnHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHapusActionPerformed
        // TODO add your handling code here:
        bgMenu.clearSelection();
        tfHarga.setText("Rp. 0");
        tfJumlah.setText("0");
        tfPesanan.setText("");
    }//GEN-LAST:event_btnHapusActionPerformed

    private void btnKeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKeluarActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_btnKeluarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(no2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(no2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(no2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(no2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new no2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup bgMenu;
    private javax.swing.JButton btnBeli;
    private javax.swing.JButton btnHapus;
    private javax.swing.JButton btnKeluar;
    private javax.swing.JButton btnKurang;
    private javax.swing.JButton btnTambah;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JRadioButton rbCapcay;
    private javax.swing.JRadioButton rbKwetiau;
    private javax.swing.JRadioButton rbMigor;
    private javax.swing.JRadioButton rbNasgor;
    private javax.swing.JRadioButton rbPangsit;
    private javax.swing.JRadioButton rbWonton;
    private javax.swing.JTextField tfHarga;
    private javax.swing.JTextField tfJumlah;
    private javax.swing.JTextArea tfPesanan;
    // End of variables declaration//GEN-END:variables
}
